export const dataJadwal = [
  //
  "Usia Dini Kata Individual Male Final",
  "Usia Dini Kumite Individual Male -30kg Final",
  "Usia Dini Kumite Individual Male +30kg Final",
  "Pra Pemula Kata Individual Male Final",
  "Pra Pemula Kata Individual Male Pool 1/2",
  "Pra Pemula Kata Individual Male Pool 2/2",
  "Pra Pemula Kata Team Male Final",
  "Pra Pemula Kumite Individual Male -35 KG Final",
  "Pra Pemula Kumite Individual Male -35 KG Pool 1/2",
  "Pra Pemula Kumite Individual Male -35 KG Pool 2/2",
  "Pra Pemula Kumite Individual Male -40 KG Final",
  "Pra Pemula Kumite Individual Male +40 KG Final",
  "Pra Pemula Kata Individual Female Final",
  "Pra Pemula Kata Individual Female Pool 1/2",
  "Pra Pemula Kata Individual Female Pool 2/2",
  "Pra Pemula Kata Team Female Final",
  "Pra Pemula Kumite Individual Female -30 KG Final",
  "Pra Pemula Kumite Individual Female -35 KG Final",
  "Pra Pemula Kumite Individual Female +35 KG Final",
  "Pemula Kata Individual Male Final",
  "Pemula Kata Individual Male Pool 1/2",
  "Pemula Kata Individual Male Pool 2/2",
  "Pemula Kata Team Male Final",
  "Pemula Kumite Individual Male -45 KG Final",
  "Pemula Kumite Individual Male -45 KG Final",
  "Pemula Kumite Individual Male -50 KG Final",
  "Pemula Kumite Individual Male -55 KG Final",
  "Pemula Kumite Individual Male +55 KG Final",
  "Pemula Kata Individual Female Final",
  "Pemula Kata Individual Female Pool 1/2",
  "Pemula Kata Individual Female Pool 2/2",
  "Pemula Kata Team Female Final",
  "Pemula Kumite Individual Female -42 KG Final",
  "Pemula Kumite Individual Female -47 KG Final",
  "Pemula Kumite Individual Female  KG Final",
  "Kadet Kata Individual Male Repechage",
  "Kadet Kumite Individual Male -52 KG Final",
  "Kadet Kumite Individual Male -52 KG Repechage",
  "Kadet Kumite Individual Male -52 KG Pool 1/2",
  "Kadet Kumite Individual Male -52 KG Pool 2/2",
  "Kadet Kumite Individual Male -57 KG Final",
  "Kadet Kumite Individual Male -63 KG Final",
  "Kadet Kumite Individual Male -70 KG Final",
  "Kadet Kumite Individual Male +70 KG Final",
  "Kadet Kumite Individual Male Best of The Best Final",
  "Kadet Kata Individual Female Repechage",
  "Kadet Kumite Individual Female -47 KG Final",
  "Kadet Kumite Individual Female -47 KG Repechage",
  "Kadet Kumite Individual Female -54 KG Final",
  "Kadet Kumite Individual Female -54 KG Repechage",
  "Kadet Kumite Individual Female -54 KG Final",
  "Kadet Kumite Individual Female -54 KG Repechage",
  "Kadet Kumite Individual Female Best of The Best Final",
  "Junior Kata Individual Male Repechage",
  "Junior Kata Team Male Repechage",
  "Junior Kumite Individual Male -55 KG Final",
  "Junior Kumite Individual Male -55 KG Repechage",
  "Junior Kumite Individual Male -55 KG Pool 1/2",
  "Junior Kumite Individual Male -55 KG Pool 2/2",
  "Junior Kumite Individual Male -61 KG Final",
  "Junior Kumite Individual Male -61 KG Repechage",
  "Junior Kumite Individual Male -68 KG Final",
  "Junior Kumite Individual Male -68 KG Repechage",
  "Junior Kumite Individual Male -68 KG Pool 1/2",
  "Junior Kumite Individual Male -68 KG Pool 2/2",
  "Junior Kumite Individual Male -76 KG Final",
  "Junior Kumite Individual Male -76 KG Repechage",
  "Junior Kumite Individual Male +76 KG Final",
  "Junior Kumite Individual Male Best of The Best Final",
  "Junior Kata Individual Female Repechage",
  "Junior Kata Team Female Repechage",
  "Junior Kumite Individual Female -48 KG Final",
  "Junior Kumite Individual Female -48 KG Repechage",
  "Junior Kumite Individual Female -53 KG Final",
  "Junior Kumite Individual Female -53 KG Repechage",
  "Junior Kumite Individual Female -59 KG Final",
  "Junior Kumite Individual Female -59 KG Repechage",
  "Junior Kumite Individual Female +59 KG Final",
  "Junior Kumite Individual Female +59 KG Repechage",
  "Junior Kumite Individual Female Best of The Best Final",
  "Senior Kata Individual Male Repechage",
  "Senior Kata Team Male Repechage",
  "Senior Kumite Individual Male -60 KG Final",
  "Senior Kumite Individual Male -60 KG Repechage",
  "Senior Kumite Individual Male -67 KG Final",
  "Senior Kumite Individual Male -67 KG Repechage",
  "Senior Kumite Individual Male -75 KG Final",
  "Senior Kumite Individual Male -84 KG Final",
  "Senior Kumite Individual Male +84 KG Final",
  "Senior Kumite Individual Male Best of The Best Final",
  "Senior Kata Individual Female Repechage",
  "Senior Kata Team Female Repechage",
  "Senior Kumite Individual Female -50 KG Final",
  "Senior Kumite Individual Female -50 KG Repechage",
  "Senior Kumite Individual Female -55 KG Final",
  "Senior Kumite Individual Female -61 KG Final",
  "Senior Kumite Individual Female -61 KG Repechage",
  "Senior Kumite Individual Female -68 KG Final",
  "Senior Kumite Individual Female Best of The Best Final",
  "Under 21 Kata Individual Male Repechage",
  "Under 21 Kata Team Male Repechage",
  "Under 21 Kumite Individual Male -60 KG Final",
  "Under 21 Kumite Individual Male -60 KG Repechage",
  "Under 21 Kumite Individual Male -67 KG Final",
  "Under 21 Kumite Individual Male -67 KG Repechage",
  "Under 21 Kumite Individual Male -75 KG Final",
  "Under 21 Kumite Individual Male -84 KG Final",
  "Under 21 Kumite Individual Male +84 KG Final",
  "Under 21 Kumite Individual Male Best of The Best Final",
  "Under 21 Kata Individual Female Repechage",
  "Under 21 Kata Team Female Repechage",
  "Under 21 Kumite Individual Female -50 KG Final",
  "Under 21 Kumite Individual Female -50 KG Repechage",
  "Under 21 Kumite Individual Female -55 KG Final",
  "Under 21 Kumite Individual Female -61 KG Final",
  "Under 21 Kumite Individual Female -61 KG Repechage",
  "Under 21 Kumite Individual Female -68 KG Final",
  "Under 21 Kumite Individual Female Best of The Best Final",
  "Veteran Kata Individual Male Final",
  "Veteran Kata Individual Female Final",
];
