import React from "react";
import { MDBTable, MDBTableBody, MDBTableHead } from "mdbreact";

const usiaDini = (props) => {
	const data_people = {
		columns: [
			{
				label: "No",
				field: "no",
				sort: "disabled",
				width: 150,
			},
			{
				label: "Entries Per Category",
				field: "EPC",
				sort: "disabled",
				width: 270,
			},
			{
				label: "Individuals",
				field: "individuals",
				sort: "disabled",
				width: 200,
			},
			{
				label: "Teams",
				field: "teams",
				sort: "disabled",
				width: 100,
			},
		],
		rows: [
			{
				no: "Tiger Nixon",
				EPC: "System Architect",
				individuals: "Edinburgh",
				teams: "61",
				date: "2011/04/25",
				salary: "$320",
			},
			{
				no: "Garrett Winters",
				EPC: "Accountant",
				individuals: "Tokyo",
				teams: "63",
				date: "2011/07/25",
				salary: "$170",
			},
			{
				no: "Ashton Cox",
				EPC: "Junior Technical Author",
				individuals: "San Francisco",
				teams: "66",
				date: "2009/01/12",
				salary: "$86",
			},
			{
				no: "Cedric Kelly",
				EPC: "Senior Javascript Developer",
				individuals: "Edinburgh",
				teams: "22",
				date: "2012/03/29",
				salary: "$433",
			},
			{
				no: "Airi Satou",
				EPC: "Accountant",
				individuals: "Tokyo",
				teams: "33",
				date: "2008/11/28",
				salary: "$162",
			},
			{
				no: "Brielle Williamson",
				EPC: "Integration Specialist",
				individuals: "New York",
				teams: "61",
				date: "2012/12/02",
				salary: "$372",
			},
			{
				no: "Herrod Chandler",
				EPC: "Sales Assistant",
				individuals: "San Francisco",
				teams: "59",
				date: "2012/08/06",
				salary: "$137",
			},
			{
				no: "Rhona Davidson",
				EPC: "Integration Specialist",
				individuals: "Tokyo",
				teams: "55",
				date: "2010/10/14",
				salary: "$327",
			},
			{
				no: "Colleen Hurst",
				EPC: "Javascript Developer",
				individuals: "San Francisco",
				teams: "39",
				date: "2009/09/15",
				salary: "$205",
			},
			{
				no: "Sonya Frost",
				EPC: "Software Engineer",
				individuals: "Edinburgh",
				teams: "23",
				date: "2008/12/13",
				salary: "$103",
			},
			{
				no: "Jena Gaines",
				EPC: "Office Manager",
				individuals: "London",
				teams: "30",
				date: "2008/12/19",
				salary: "$90",
			},
			{
				no: "Quinn Flynn",
				EPC: "Support Lead",
				individuals: "Edinburgh",
				teams: "22",
				date: "2013/03/03",
				salary: "$342",
			},
			{
				no: "Charde Marshall",
				EPC: "Regional Director",
				individuals: "San Francisco",
				teams: "36",
				date: "2008/10/16",
				salary: "$470",
			},
			{
				no: "Haley Kennedy",
				EPC: "Senior Marketing Designer",
				individuals: "London",
				teams: "43",
				date: "2012/12/18",
				salary: "$313",
			},
			{
				no: "Tatyana Fitzpatrick",
				EPC: "Regional Director",
				individuals: "London",
				teams: "19",
				date: "2010/03/17",
				salary: "$385",
			},
			{
				no: "Michael Silva",
				EPC: "Marketing Designer",
				individuals: "London",
				teams: "66",
				date: "2012/11/27",
				salary: "$198",
			},
			{
				no: "Paul Byrd",
				EPC: "Chief Financial Officer (CFO)",
				individuals: "New York",
				teams: "64",
				date: "2010/06/09",
				salary: "$725",
			},
			{
				no: "Gloria Little",
				EPC: "Systems Administrator",
				individuals: "New York",
				teams: "59",
				date: "2009/04/10",
				salary: "$237",
			},
			{
				no: "Bradley Greer",
				EPC: "Software Engineer",
				individuals: "London",
				teams: "41",
				date: "2012/10/13",
				salary: "$132",
			},
			{
				no: "Dai Rios",
				EPC: "Personnel Lead",
				individuals: "Edinburgh",
				teams: "35",
				date: "2012/09/26",
				salary: "$217",
			},
			{
				no: "Jenette Caldwell",
				EPC: "Development Lead",
				individuals: "New York",
				teams: "30",
				date: "2011/09/03",
				salary: "$345",
			},
			{
				no: "Yuri Berry",
				EPC: "Chief Marketing Officer (CMO)",
				individuals: "New York",
				teams: "40",
				date: "2009/06/25",
				salary: "$675",
			},
			{
				no: "Caesar Vance",
				EPC: "Pre-Sales Support",
				individuals: "New York",
				teams: "21",
				date: "2011/12/12",
				salary: "$106",
			},
			{
				no: "Doris Wilder",
				EPC: "Sales Assistant",
				individuals: "Sidney",
				teams: "23",
				date: "2010/09/20",
				salary: "$85",
			},
			{
				no: "Angelica Ramos",
				EPC: "Chief Executive Officer (CEO)",
				individuals: "London",
				teams: "47",
				date: "2009/10/09",
				salary: "$1",
			},
			{
				no: "Gavin Joyce",
				EPC: "Developer",
				individuals: "Edinburgh",
				teams: "42",
				date: "2010/12/22",
				salary: "$92",
			},
			{
				no: "Jennifer Chang",
				EPC: "Regional Director",
				individuals: "Singapore",
				teams: "28",
				date: "2010/11/14",
				salary: "$357",
			},
			{
				no: "Brenden Wagner",
				EPC: "Software Engineer",
				individuals: "San Francisco",
				teams: "28",
				date: "2011/06/07",
				salary: "$206",
			},
			{
				no: "Fiona Green",
				EPC: "Chief Operating Officer (COO)",
				individuals: "San Francisco",
				teams: "48",
				date: "2010/03/11",
				salary: "$850",
			},
			{
				no: "Shou Itou",
				EPC: "Regional Marketing",
				individuals: "Tokyo",
				teams: "20",
				date: "2011/08/14",
				salary: "$163",
			},
			{
				no: "Michelle House",
				EPC: "Integration Specialist",
				individuals: "Sidney",
				teams: "37",
				date: "2011/06/02",
				salary: "$95",
			},
			{
				no: "Suki Burks",
				EPC: "Developer",
				individuals: "London",
				teams: "53",
				date: "2009/10/22",
				salary: "$114",
			},
			{
				no: "Prescott Bartlett",
				EPC: "Technical Author",
				individuals: "London",
				teams: "27",
				date: "2011/05/07",
				salary: "$145",
			},
			{
				no: "Gavin Cortez",
				EPC: "Team Leader",
				individuals: "San Francisco",
				teams: "22",
				date: "2008/10/26",
				salary: "$235",
			},
			{
				no: "Martena Mccray",
				EPC: "Post-Sales support",
				individuals: "Edinburgh",
				teams: "46",
				date: "2011/03/09",
				salary: "$324",
			},
			{
				no: "Unity Butler",
				EPC: "Marketing Designer",
				individuals: "San Francisco",
				teams: "47",
				date: "2009/12/09",
				salary: "$85",
			},
			{
				no: "Howard Hatfield",
				EPC: "Office Manager",
				individuals: "San Francisco",
				teams: "51",
				date: "2008/12/16",
				salary: "$164",
			},
			{
				no: "Hope Fuentes",
				EPC: "Secretary",
				individuals: "San Francisco",
				teams: "41",
				date: "2010/02/12",
				salary: "$109",
			},
			{
				no: "Vivian Harrell",
				EPC: "Financial Controller",
				individuals: "San Francisco",
				teams: "62",
				date: "2009/02/14",
				salary: "$452",
			},
			{
				no: "Timothy Mooney",
				EPC: "Office Manager",
				individuals: "London",
				teams: "37",
				date: "2008/12/11",
				salary: "$136",
			},
			{
				no: "Jackson Bradshaw",
				EPC: "Director",
				individuals: "New York",
				teams: "65",
				date: "2008/09/26",
				salary: "$645",
			},
			{
				no: "Olivia Liang",
				EPC: "Support Engineer",
				individuals: "Singapore",
				teams: "64",
				date: "2011/02/03",
				salary: "$234",
			},
			{
				no: "Bruno Nash",
				EPC: "Software Engineer",
				individuals: "London",
				teams: "38",
				date: "2011/05/03",
				salary: "$163",
			},
			{
				no: "Sakura Yamamoto",
				EPC: "Support Engineer",
				individuals: "Tokyo",
				teams: "37",
				date: "2009/08/19",
				salary: "$139",
			},
			{
				no: "Thor Walton",
				EPC: "Developer",
				individuals: "New York",
				teams: "61",
				date: "2013/08/11",
				salary: "$98",
			},
			{
				no: "Finn Camacho",
				EPC: "Support Engineer",
				individuals: "San Francisco",
				teams: "47",
				date: "2009/07/07",
				salary: "$87",
			},
			{
				no: "Serge Baldwin",
				EPC: "Data Coordinator",
				individuals: "Singapore",
				teams: "64",
				date: "2012/04/09",
				salary: "$138",
			},
			{
				no: "Zenaida Frank",
				EPC: "Software Engineer",
				individuals: "New York",
				teams: "63",
				date: "2010/01/04",
				salary: "$125",
			},
			{
				no: "Zorita Serrano",
				EPC: "Software Engineer",
				individuals: "San Francisco",
				teams: "56",
				date: "2012/06/01",
				salary: "$115",
			},
			{
				no: "Jennifer Acosta",
				EPC: "Junior Javascript Developer",
				individuals: "Edinburgh",
				teams: "43",
				date: "2013/02/01",
				salary: "$75",
			},
			{
				no: "Cara Stevens",
				EPC: "Sales Assistant",
				individuals: "New York",
				teams: "46",
				date: "2011/12/06",
				salary: "$145",
			},
			{
				no: "Hermione Butler",
				EPC: "Regional Director",
				individuals: "London",
				teams: "47",
				date: "2011/03/21",
				salary: "$356",
			},
			{
				no: "Lael Greer",
				EPC: "Systems Administrator",
				individuals: "London",
				teams: "21",
				date: "2009/02/27",
				salary: "$103",
			},
			{
				no: "Jonas Alexander",
				EPC: "Developer",
				individuals: "San Francisco",
				teams: "30",
				date: "2010/07/14",
				salary: "$86",
			},
			{
				no: "Shad Decker",
				EPC: "Regional Director",
				individuals: "Edinburgh",
				teams: "51",
				date: "2008/11/13",
				salary: "$183",
			},
			{
				no: "Michael Bruce",
				EPC: "Javascript Developer",
				individuals: "Singapore",
				teams: "29",
				date: "2011/06/27",
				salary: "$183",
			},
			{
				no: "Donna Snider",
				EPC: "Customer Support",
				individuals: "New York",
				teams: "27",
				date: "2011/01/25",
				salary: "$112",
			},
		],
	};
	return data_people;
};

export { usiaDini };
