import React from "react";
import { MDBTable, MDBTableBody, MDBTableHead } from "mdbreact";

	const data = {
		columns: [
			{
				label: "Name",
				field: "name",
				sort: "asc",
				width: 150,
			},
			{
				label: "Position",
				field: "position",
				sort: "asc",
				width: 270,
			},
			{
				label: "Office",
				field: "office",
				sort: "asc",
				width: 200,
			},
			{
				label: "Age",
				field: "age",
				sort: "asc",
				width: "200",
			},
			{
				label: "Date",
				field: "date",
				sort: "asc",
				width: "200",
			},
			{
				label: "Salary",
				field: "salary",
				sort: "asc",
				width: "200",
			},
		],
		rows: [
			{
				name: "Tiger Nixon",
				position: "System Architect",
				teams: "Edinburgh",
				Age: "61",
				date: "2011/04/25",
				salary: "$320",
			},
			{
				name: "Garrett Winters",
				EPC: "Accountant",
				teams: "Tokyo",
				age: "63",
				date: "2011/07/25",
				salary: "$170",
			},
			{
				name: "Ashton Cox",
				EPC: "Junior Technical Author",
				teams: "San Francisco",
				age: "66",
				date: "2009/01/12",
				salary: "$86",
			},
			{
				name: "Cedric Kelly",
				EPC: "Senior Javascript Developer",
				teams: "Edinburgh",
				age: "22",
				date: "2012/03/29",
				salary: "$433",
			},
			{
				name: "Airi Satou",
				EPC: "Accountant",
				teams: "Tokyo",
				age: "33",
				date: "2008/11/28",
				salary: "$162",
			},
			{
				name: "Brielle Williamson",
				EPC: "Integration Specialist",
				teams: "New York",
				age: "61",
				date: "2012/12/02",
				salary: "$372",
			},
			{
				name: "Herrod Chandler",
				EPC: "Sales Assistant",
				teams: "San Francisco",
				age: "59",
				date: "2012/08/06",
				salary: "$137",
			},
			{
				name: "Rhona Davidson",
				EPC: "Integration Specialist",
				teams: "Tokyo",
				age: "55",
				date: "2010/10/14",
				salary: "$327",
			},
			{
				name: "Colleen Hurst",
				EPC: "Javascript Developer",
				teams: "San Francisco",
				age: "39",
				date: "2009/09/15",
				salary: "$205",
			},
			{
				name: "Sonya Frost",
				EPC: "Software Engineer",
				teams: "Edinburgh",
				age: "23",
				date: "2008/12/13",
				salary: "$103",
			},
			{
				name: "Jena Gaines",
				EPC: "Office Manager",
				teams: "London",
				age: "30",
				date: "2008/12/19",
				salary: "$90",
			},
			{
				name: "Quinn Flynn",
				EPC: "Support Lead",
				teams: "Edinburgh",
				age: "22",
				date: "2013/03/03",
				salary: "$342",
			},
			{
				name: "Charde Marshall",
				EPC: "Regional Director",
				teams: "San Francisco",
				age: "36",
				date: "2008/10/16",
				salary: "$470",
			},
			{
				name: "Haley Kennedy",
				EPC: "Senior Marketing Designer",
				teams: "London",
				age: "43",
				date: "2012/12/18",
				salary: "$313",
			},
			{
				name: "Tatyana Fitzpatrick",
				EPC: "Regional Director",
				teams: "London",
				age: "19",
				date: "2010/03/17",
				salary: "$385",
			},
			{
				name: "Michael Silva",
				EPC: "Marketing Designer",
				teams: "London",
				age: "66",
				date: "2012/11/27",
				salary: "$198",
			},
			{
				name: "Paul Byrd",
				EPC: "Chief Financial Officer (CFO)",
				teams: "New York",
				age: "64",
				date: "2010/06/09",
				salary: "$725",
			},
			{
				name: "Gloria Little",
				EPC: "Systems Administrator",
				teams: "New York",
				age: "59",
				date: "2009/04/10",
				salary: "$237",
			},
			{
				name: "Bradley Greer",
				EPC: "Software Engineer",
				teams: "London",
				age: "41",
				date: "2012/10/13",
				salary: "$132",
			},
			{
				name: "Dai Rios",
				EPC: "Personnel Lead",
				teams: "Edinburgh",
				age: "35",
				date: "2012/09/26",
				salary: "$217",
			},
			{
				name: "Jenette Caldwell",
				EPC: "Development Lead",
				teams: "New York",
				age: "30",
				date: "2011/09/03",
				salary: "$345",
			},
			{
				name: "Yuri Berry",
				EPC: "Chief Marketing Officer (CMO)",
				teams: "New York",
				age: "40",
				date: "2009/06/25",
				salary: "$675",
			},
			{
				name: "Caesar Vance",
				EPC: "Pre-Sales Support",
				teams: "New York",
				age: "21",
				date: "2011/12/12",
				salary: "$106",
			},
			{
				name: "Doris Wilder",
				EPC: "Sales Assistant",
				teams: "Sidney",
				age: "23",
				date: "2010/09/20",
				salary: "$85",
			},
			{
				name: "Angelica Ramos",
				EPC: "Chief Executive Officer (CEO)",
				teams: "London",
				age: "47",
				date: "2009/10/09",
				salary: "$1",
			},
			{
				name: "Gavin Joyce",
				EPC: "Developer",
				teams: "Edinburgh",
				age: "42",
				date: "2010/12/22",
				salary: "$92",
			},
			{
				name: "Jennifer Chang",
				EPC: "Regional Director",
				teams: "Singapore",
				age: "28",
				date: "2010/11/14",
				salary: "$357",
			},
			{
				name: "Brenden Wagner",
				EPC: "Software Engineer",
				teams: "San Francisco",
				age: "28",
				date: "2011/06/07",
				salary: "$206",
			},
			{
				name: "Fiona Green",
				EPC: "Chief Operating Officer (COO)",
				teams: "San Francisco",
				age: "48",
				date: "2010/03/11",
				salary: "$850",
			},
			{
				name: "Shou Itou",
				EPC: "Regional Marketing",
				teams: "Tokyo",
				age: "20",
				date: "2011/08/14",
				salary: "$163",
			},
			{
				name: "Michelle House",
				EPC: "Integration Specialist",
				teams: "Sidney",
				age: "37",
				date: "2011/06/02",
				salary: "$95",
			},
			{
				name: "Suki Burks",
				EPC: "Developer",
				teams: "London",
				age: "53",
				date: "2009/10/22",
				salary: "$114",
			},
			{
				name: "Prescott Bartlett",
				EPC: "Technical Author",
				teams: "London",
				age: "27",
				date: "2011/05/07",
				salary: "$145",
			},
			{
				name: "Gavin Cortez",
				EPC: "Team Leader",
				teams: "San Francisco",
				age: "22",
				date: "2008/10/26",
				salary: "$235",
			},
			{
				name: "Martena Mccray",
				EPC: "Post-Sales support",
				teams: "Edinburgh",
				age: "46",
				date: "2011/03/09",
				salary: "$324",
			},
			{
				name: "Unity Butler",
				EPC: "Marketing Designer",
				teams: "San Francisco",
				age: "47",
				date: "2009/12/09",
				salary: "$85",
			},
			{
				name: "Howard Hatfield",
				EPC: "Office Manager",
				teams: "San Francisco",
				age: "51",
				date: "2008/12/16",
				salary: "$164",
			},
			{
				name: "Hope Fuentes",
				EPC: "Secretary",
				teams: "San Francisco",
				age: "41",
				date: "2010/02/12",
				salary: "$109",
			},
			{
				name: "Vivian Harrell",
				EPC: "Financial Controller",
				teams: "San Francisco",
				age: "62",
				date: "2009/02/14",
				salary: "$452",
			},
			{
				name: "Timothy Mooney",
				EPC: "Office Manager",
				teams: "London",
				age: "37",
				date: "2008/12/11",
				salary: "$136",
			},
			{
				name: "Jackson Bradshaw",
				EPC: "Director",
				teams: "New York",
				age: "65",
				date: "2008/09/26",
				salary: "$645",
			},
			{
				name: "Olivia Liang",
				EPC: "Support Engineer",
				teams: "Singapore",
				age: "64",
				date: "2011/02/03",
				salary: "$234",
			},
			{
				name: "Bruname Nash",
				EPC: "Software Engineer",
				teams: "London",
				age: "38",
				date: "2011/05/03",
				salary: "$163",
			},
			{
				name: "Sakura Yamamoto",
				EPC: "Support Engineer",
				teams: "Tokyo",
				age: "37",
				date: "2009/08/19",
				salary: "$139",
			},
			{
				name: "Thor Walton",
				EPC: "Developer",
				teams: "New York",
				age: "61",
				date: "2013/08/11",
				salary: "$98",
			},
			{
				name: "Finn Camacho",
				EPC: "Support Engineer",
				teams: "San Francisco",
				age: "47",
				date: "2009/07/07",
				salary: "$87",
			},
			{
				name: "Serge Baldwin",
				EPC: "Data Coordinator",
				teams: "Singapore",
				age: "64",
				date: "2012/04/09",
				salary: "$138",
			},
			{
				name: "Zenaida Frank",
				EPC: "Software Engineer",
				teams: "New York",
				age: "63",
				date: "2010/01/04",
				salary: "$125",
			},
			{
				name: "Zorita Serrano",
				EPC: "Software Engineer",
				teams: "San Francisco",
				age: "56",
				date: "2012/06/01",
				salary: "$115",
			},
			{
				name: "Jennifer Acosta",
				EPC: "Junior Javascript Developer",
				teams: "Edinburgh",
				age: "43",
				date: "2013/02/01",
				salary: "$75",
			},
			{
				name: "Cara Stevens",
				EPC: "Sales Assistant",
				teams: "New York",
				age: "46",
				date: "2011/12/06",
				salary: "$145",
			},
			{
				name: "Hermione Butler",
				EPC: "Regional Director",
				teams: "London",
				age: "47",
				date: "2011/03/21",
				salary: "$356",
			},
			{
				name: "Lael Greer",
				EPC: "Systems Administrator",
				teams: "London",
				age: "21",
				date: "2009/02/27",
				salary: "$103",
			},
			{
				name: "Jonas Alexander",
				EPC: "Developer",
				teams: "San Francisco",
				age: "30",
				date: "2010/07/14",
				salary: "$86",
			},
			{
				name: "Shad Decker",
				EPC: "Regional Director",
				teams: "Edinburgh",
				age: "51",
				date: "2008/11/13",
				salary: "$183",
			},
			{
				name: "Michael Bruce",
				EPC: "Javascript Developer",
				teams: "Singapore",
				age: "29",
				date: "2011/06/27",
				salary: "$183",
			},
			{
				name: "Donna Snider",
				EPC: "Customer Support",
				teams: "New York",
				age: "27",
				date: "2011/01/25",
				salary: "$112",
			},
		],
};

export { data };
